version: '3.1'

services:

  mongo:
    image: mongo:5
    restart: always
    volumes:
      - mongo:/data/db

  back:
    build: .
    ports:
      - 8091:9090
    environment:
      PORT: 9090
      MONGO_URL: mongodb://mongo:27017/ExamenNodejs
    depends_on:
      - mongo
